name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Code Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Running Tests
        run: npm run test
      - name: Uploading Coverage
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN2 }}

  deploy:
    if: success()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment via private URL
        run: |
          curl -X GET "${{ secrets.PRIVATE_DEPLOY_URL }}"
