name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/portfolio-backend:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}/portfolio-backend:${{ github.sha }} ghcr.io/${{ github.repository }}/my-app:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/portfolio-backend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/portfolio-backend:latest
