name: Pr-Check
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-comment:
    name: Build and Post Coverage Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Run Tests and Generate Coverage
        run: npm run test
      - name: Extract Coverage Summary
        id: coverage
        run: |
          # Capture the text summary from the coverage report
          summary=$(cat coverage/lcov-report/index.html | head -n 20)
          echo "COVERAGE_SUMMARY<<EOF" >> $GITHUB_ENV
          echo "$summary" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Comment on PR with Coverage
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            **Test Coverage Report**
            ```
            ${{ env.COVERAGE_SUMMARY }}
            ```
