name: Pr-Check
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewers
        uses: ahmadnassri/action-add-reviewers@v2.1.0
        with:
          reviewers: 'rohitsaw'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-comment:
    name: Extract Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Extract Coverage Summary
        id: coverage
        run: |
          # Read the captured text-summary from the coverage output
          summary=$(npm run test -- --coverageReporters=text-summary | tee coverage-summary.txt | tail -n +2)
          echo "COVERAGE_SUMMARY<<EOF" >> $GITHUB_ENV
          echo "$summary" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Comment on PR with Coverage
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            **Test Coverage Report**
            ```
            ${{ env.COVERAGE_SUMMARY }}
            ```
